#nullable disable
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TekTomato.Data;

namespace TekTomato.Data.Migrations
{
    /// <summary>
    /// Snapshot of the EF Core model. Auto-generated by tooling.
    /// </summary>
    [DbContext(typeof(TekTomatoDbContext))]
    [Migration("20260313000001_InitialCreate")]
    partial class TekTomatoDbContextModelSnapshot : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("TekTomato.Models.PomodoroSession", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ActualDurationSeconds")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CompletedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<bool>("CompletedNormally")
                    .HasDefaultValue(true)
                    .HasColumnType("INTEGER");

                b.Property<int>("OverrunSeconds")
                    .HasDefaultValue(0)
                    .HasColumnType("INTEGER");

                b.Property<int>("PausedDurationSeconds")
                    .HasDefaultValue(0)
                    .HasColumnType("INTEGER");

                b.Property<int>("PlannedDurationSeconds")
                    .HasColumnType("INTEGER");

                b.Property<int?>("PomodoroNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("SessionType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("StartedAtUtc")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SessionType", "CompletedNormally")
                    .HasDatabaseName("IX_Sessions_SessionType_CompletedNormally");

                b.HasIndex("StartedAtUtc")
                    .HasDatabaseName("IX_Sessions_StartedAtUtc");

                b.ToTable("Sessions");
            });

            modelBuilder.Entity("TekTomato.Models.Setting", b =>
            {
                b.Property<string>("Key")
                    .ValueGeneratedNever()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.HasKey("Key");

                b.ToTable("Settings");
            });
#pragma warning restore 612, 618
        }
    }
}